services:
  segformer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pie-sxs
    shm_size: "8g"
    env_file:
      - .env
    volumes:
      - ${TRAIN_DATA_DIR}:/app/data/brats2017_seg/brats2017_raw_data/train
      - ${PROCESSED_DATA_DIR}:/app/data/brats2017_seg/BraTS2017_Training_Data
      - ${OUTPUT_DIR}:/app/data/output
    tty: true
    stdin_open: true
    command: ["all"]  # Default: run all steps. Override with: docker compose run app <command>