services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pie-sxs
    env_file:
      - .env
    volumes:
      - ${DATA_DIR}:/app/data/
    tty: true
    stdin_open: true